defmodule Froth.Telemetry do
  @moduledoc """
  Central telemetry event registry.

  Defines all [:froth, **] event names and attaches the Logger,
  Store, and Broadcaster handlers on application startup.
  """

  @http_events [
    [:froth, :http, :request, :start],
    [:froth, :http, :request, :stop],
    [:froth, :http, :request, :exception],
    [:froth, :http, :sse, :http_status],
    [:froth, :http, :sse, :message_start],
    [:froth, :http, :sse, :message_stop],
    [:froth, :http, :sse, :thinking_start],
    [:froth, :http, :sse, :thinking_stop],
    [:froth, :http, :sse, :thinking_delta],
    [:froth, :http, :sse, :tool_use_start],
    [:froth, :http, :sse, :tool_use_stop],
    [:froth, :http, :sse, :tool_use_delta],
    [:froth, :http, :sse, :tool_result],
    [:froth, :http, :sse, :text_delta],
    [:froth, :http, :sse, :usage]
  ]

  @anthropic_events [
    [:froth, :anthropic, :request, :start],
    [:froth, :anthropic, :request, :stop],
    [:froth, :anthropic, :request, :exception]
  ]

  @agent_events [
    [:froth, :agent, :cycle, :start],
    [:froth, :agent, :cycle, :stop],
    [:froth, :agent, :think, :start],
    [:froth, :agent, :think, :stop]
  ]

  @telegram_events [
    [:froth, :telegram, :auto_start],
    [:froth, :telegram, :auth, :ignored],
    [:froth, :telegram, :session, :start],
    [:froth, :telegram, :session, :stop],
    [:froth, :telegram, :bot, :listening],
    [:froth, :telegram, :bot, :update],
    [:froth, :telegram, :bot, :cycle, :start],
    [:froth, :telegram, :bot, :cycle, :stop],
    [:froth, :telegram, :bot, :busy],
    [:froth, :telegram, :bot_adapter, :chat_access_check],
    [:froth, :telegram, :bots, :autostart_failed],
    [:froth, :telegram, :bots, :start_failed],
    [:froth, :telegram, :session, :no_distribution],
    [:froth, :telegram, :session, :registered],
    [:froth, :telegram, :session, :register_failed],
    [:froth, :telegram, :session, :sync_auth],
    [:froth, :telegram, :session, :already_connected],
    [:froth, :telegram, :session, :connected],
    [:froth, :telegram, :session, :disconnected],
    [:froth, :telegram, :session, :tgcalls_sink_restarted],
    [:froth, :telegram, :session, :tgcalls_route_failed],
    [:froth, :telegram, :session, :unexpected],
    [:froth, :telegram, :session, :set_tdlib_params],
    [:froth, :telegram, :session, :check_encryption_key],
    [:froth, :telegram, :session, :auth_bot_token],
    [:froth, :telegram, :session, :auth_phone],
    [:froth, :telegram, :session, :no_credentials],
    [:froth, :telegram, :session, :ready],
    [:froth, :telegram, :session, :auth_state],
    [:froth, :telegram, :session, :send_failed],
    [:froth, :telegram, :cnode, :no_distribution],
    [:froth, :telegram, :cnode, :register],
    [:froth, :telegram, :cnode, :unknown_session],
    [:froth, :telegram, :cnode, :not_connected],
    [:froth, :telegram, :cnode, :unregister],
    [:froth, :telegram, :cnode, :connected],
    [:froth, :telegram, :cnode, :launching],
    [:froth, :telegram, :cnode, :connect_retry],
    [:froth, :telegram, :cnode, :node_up],
    [:froth, :telegram, :cnode, :node_down],
    [:froth, :telegram, :cnode, :exited],
    [:froth, :telegram, :cnode, :output],
    [:froth, :telegram, :cnode, :unexpected],
    [:froth, :telegram, :cnode, :reinit],
    [:froth, :telegram, :cnode, :reinit_session],
    [:froth, :telegram, :cnode, :disconnecting],
    [:froth, :telegram, :cnode, :disconnect_session],
    [:froth, :telegram, :cnode, :missing_executable],
    [:froth, :telegram, :cnode, :kill_stale],
    [:froth, :telegram, :sync, :backfill_start],
    [:froth, :telegram, :sync, :backfill_chats],
    [:froth, :telegram, :sync, :backfill_done],
    [:froth, :telegram, :sync, :backfill_round],
    [:froth, :telegram, :sync, :backfill_chat_done],
    [:froth, :telegram, :sync, :backfill_error],
    [:froth, :telegram, :sync, :backfill_empty],
    [:froth, :telegram, :sync, :backfill_stored],
    [:froth, :telegram, :sync, :listening],
    [:froth, :telegram, :sync, :store_failed],
    [:froth, :telegram, :call_qwen, :bridge_started],
    [:froth, :telegram, :call_qwen, :media_event],
    [:froth, :telegram, :call_qwen, :media_error],
    [:froth, :telegram, :call_qwen, :feed_failed],
    [:froth, :telegram, :call_qwen, :tts_done],
    [:froth, :telegram, :call_qwen, :asr_partial],
    [:froth, :telegram, :call_qwen, :asr_final],
    [:froth, :telegram, :call_qwen, :asr_speech_started],
    [:froth, :telegram, :call_qwen, :asr_speech_stopped],
    [:froth, :telegram, :call_qwen, :ws_error],
    [:froth, :telegram, :call_qwen, :ws_finished],
    [:froth, :telegram, :call_qwen, :asr_down],
    [:froth, :telegram, :call_qwen, :tts_down],
    [:froth, :telegram, :call_qwen, :tts_say]
  ]

  @codex_events [
    [:froth, :codex, :pubsub_subscribe],
    [:froth, :codex, :pubsub_unsubscribe],
    [:froth, :codex, :started],
    [:froth, :codex, :start_failed],
    [:froth, :codex, :notify_send],
    [:froth, :codex, :notify_sent],
    [:froth, :codex, :notify_failed],
    [:froth, :codex, :request_send],
    [:froth, :codex, :request_queued],
    [:froth, :codex, :request_failed_to_send],
    [:froth, :codex, :data_chunk],
    [:froth, :codex, :server_exited],
    [:froth, :codex, :request_timeout],
    [:froth, :codex, :terminate],
    [:froth, :codex, :response_received],
    [:froth, :codex, :notification_received],
    [:froth, :codex, :unknown_message],
    [:froth, :codex, :invalid_json],
    [:froth, :codex, :unexpected_response],
    [:froth, :codex, :request_error_response],
    [:froth, :codex, :request_ok_response],
    [:froth, :codex, :send_raw],
    [:froth, :codex, :send_failed],
    [:froth, :codex, :fail_pending],
    [:froth, :codex, :task_started],
    [:froth, :codex, :session_codex_exit],
    [:froth, :codex, :notification_failed],
    [:froth, :codex, :events_load_failed],
    [:froth, :codex, :events_list_failed],
    [:froth, :codex, :events_upsert_failed],
    [:froth, :codex, :raw_events_list_failed],
    [:froth, :codex, :raw_events_append_failed]
  ]

  @other_events [
    [:froth, :qwen, :connected],
    [:froth, :qwen, :in],
    [:froth, :qwen, :ws_closed],
    [:froth, :qwen, :ws_client_down],
    [:froth, :qwen, :audio_before_session],
    [:froth, :qwen, :audio_resumed],
    [:froth, :qwen, :audio_rate_change],
    [:froth, :qwen, :session_created],
    [:froth, :qwen, :session_updated],
    [:froth, :qwen, :item_created],
    [:froth, :qwen, :audio_committed],
    [:froth, :qwen, :unhandled_event],
    [:froth, :qwen, :ws_error],
    [:froth, :qwen, :resample_failed],
    [:froth, :qwen, :out],
    [:froth, :tasks, :created],
    [:froth, :tasks, :started],
    [:froth, :tasks, :completed],
    [:froth, :tasks, :failed],
    [:froth, :tasks, :stopped],
    [:froth, :tasks, :notification_fired],
    [:froth, :tasks, :eval_started],
    [:froth, :tasks, :eval_done],
    [:froth, :tasks, :eval_crashed],
    [:froth, :tasks, :shell_started],
    [:froth, :tasks, :shell_signal],
    [:froth, :tasks, :shell_exited],
    [:froth, :tasks, :shell_unexpected_message],
    [:froth, :dataset, :auto_loaded],
    [:froth, :dataset, :auto_load_failed],
    [:froth, :dataset, :auto_load_complete],
    [:froth, :dataset, :loaded],
    [:froth, :replicate, :using_version],
    [:froth, :replicate, :readme_fetched],
    [:froth, :replicate, :readme_not_found],
    [:froth, :replicate, :readme_fetch_failed],
    [:froth, :replicate, :github_redirect],
    [:froth, :replicate, :github_rate_limited],
    [:froth, :replicate, :collection_synced],
    [:froth, :replicate, :sync_enqueued],
    [:froth, :podcast, :already_downloaded],
    [:froth, :podcast, :downloading],
    [:froth, :podcast, :complete],
    [:froth, :podcast, :segment_done],
    [:froth, :web, :room_joined],
    [:froth, :web, :sample_rate_changed],
    [:froth, :web, :invalid_sample_rate],
    [:froth, :web, :asr_started],
    [:froth, :web, :asr_start_failed],
    [:froth, :web, :asr_buffer_committed],
    [:froth, :web, :asr_stopped],
    [:froth, :web, :unhandled_channel_event],
    [:froth, :web, :asr_process_died],
    [:froth, :web, :mount_connected],
    [:froth, :web, :send_prompt],
    [:froth, :web, :new_thread],
    [:froth, :web, :interrupt_turn],
    [:froth, :web, :connect_failed],
    [:froth, :web, :snapshot_failed],
    [:froth, :web, :miniapp_log],
    [:froth, :web, :miniapp_params],
    [:froth, :ws_proto, :connecting],
    [:froth, :ws_proto, :upgrade_sent],
    [:froth, :ws_proto, :connect_failed],
    [:froth, :ws_proto, :raw_recv],
    [:froth, :ws_proto, :connected],
    [:froth, :ws_proto, :upgrade_failed],
    [:froth, :ws_proto, :ping],
    [:froth, :ws_proto, :recv_close],
    [:froth, :ws_proto, :closed],
    [:froth, :ws_proto, :socket_error],
    [:froth, :ws_proto, :send_done],
    [:froth, :ws_proto, :send_failed],
    [:froth, :ws_proto, :unhandled]
  ]

  @all_events @http_events ++
                @anthropic_events ++
                @agent_events ++
                @telegram_events ++
                @codex_events ++
                @other_events

  def events, do: @all_events

  def attach_handlers do
    Froth.Telemetry.Logger.attach(@all_events)
    Froth.Telemetry.Store.attach(@all_events)
    Froth.Telemetry.Broadcaster.attach(@anthropic_events ++ @http_events)
  end
end
