defmodule Froth.AnthropicTest do
  use Froth.AnthropicCase, async: false

  alias Froth.Anthropic

  describe "stream_reply_with_tools/2 with simple text fixture" do
    test "returns accumulated text and api_messages" do
      Application.put_env(:froth, :sse_stream_fun, Froth.SSEReplay.stream_fun("simple_reply"))

      {:ok, %{text: text, api_messages: api_messages, usage: usage}} =
        Anthropic.stream_reply_with_tools(
          [%{role: :user, text: "hello"}],
          fn _event -> :ok end
        )

      assert text =~ "transistor"
      assert text =~ "1947"
      assert length(api_messages) == 2
      assert Enum.at(api_messages, 0)["role"] == "user"
      assert Enum.at(api_messages, 1)["role"] == "assistant"
      assert usage["input_tokens"] == 18
      assert usage["output_tokens"] == 36
    end

    test "emits text_delta events" do
      Application.put_env(:froth, :sse_stream_fun, Froth.SSEReplay.stream_fun("simple_reply"))

      pid = self()

      {:ok, _} =
        Anthropic.stream_reply_with_tools(
          [%{role: :user, text: "hello"}],
          fn event -> send(pid, {:event, event}) end
        )

      deltas = collect_events(:text_delta)
      assert length(deltas) > 0
      full_text = deltas |> Enum.map(fn {:text_delta, t} -> t end) |> Enum.join()
      assert full_text =~ "transistor"
    end
  end

  describe "stream_reply_with_tools/2 with tool use fixture" do
    test "executes tool loop and returns final text and api_messages" do
      Application.put_env(:froth, :sse_stream_fun, Froth.SSEReplay.stream_fun("tool_use_echo"))

      pid = self()

      echo_tool = fn
        "froth_echo", %{"text" => t} -> {:ok, t}
        _, _ -> {:error, "unknown"}
      end

      {:ok, %{text: text, api_messages: api_messages, usage: usage}} =
        Anthropic.stream_reply_with_tools(
          [%{role: :user, text: "echo test"}],
          fn event -> send(pid, {:event, event}) end,
          on_tool: echo_tool
        )

      assert is_binary(text)
      assert text =~ "test message"

      # api_messages should contain: user, assistant (tool_use), user (tool_result), assistant (text)
      roles = Enum.map(api_messages, & &1["role"])
      assert roles == ["user", "assistant", "user", "assistant"]
      assert usage["input_tokens"] == 1328
      assert usage["output_tokens"] == 52

      # Tool use events from turn 0
      assert_received {:event, {:tool_use_start, %{"name" => "froth_echo"}}}

      assert_received {:event,
                       {:tool_use_stop,
                        %{"name" => "froth_echo", "input" => %{"text" => "test message"}}}}

      # Tool result event (generated by the tool loop)
      assert_received {:event,
                       {:tool_result,
                        %{
                          "name" => "froth_echo",
                          "content" => "test message",
                          "is_error" => false
                        }}}
    end
  end

  describe "stream_reply_with_tools/2 with thinking fixture" do
    test "processes thinking blocks and returns text with api_messages" do
      Application.put_env(:froth, :sse_stream_fun, Froth.SSEReplay.stream_fun("thinking_reply"))

      pid = self()

      {:ok, %{text: text, api_messages: api_messages}} =
        Anthropic.stream_reply_with_tools(
          [%{role: :user, text: "what is 2+2?"}],
          fn event -> send(pid, {:event, event}) end
        )

      assert text =~ "2 + 2"

      # api_messages should have assistant with thinking + text content
      assistant = Enum.find(api_messages, &(&1["role"] == "assistant"))
      assert is_list(assistant["content"])
      assert Enum.any?(assistant["content"], &(&1["type"] == "thinking"))
      assert Enum.any?(assistant["content"], &(&1["type"] == "text"))

      # Thinking events should have been emitted
      assert_received {:event, {:thinking_start, %{"index" => 0}}}
      assert_received {:event, {:thinking_stop, %{"index" => 0, "thinking" => thinking}}}
      assert thinking =~ "2"
    end
  end

  describe "prompt caching payload passthrough" do
    test "sends cache_control blocks unchanged to Anthropic" do
      pid = self()

      Application.put_env(
        :froth,
        :sse_stream_fun,
        Froth.SSEReplay.recording_stream_fun("simple_reply", pid)
      )

      history = [
        %{
          "role" => "user",
          "content" => [
            %{
              "type" => "text",
              "text" => "<cached_context>stable</cached_context>",
              "cache_control" => %{"type" => "ephemeral", "ttl" => "1h"}
            },
            %{"type" => "text", "text" => "\n<dynamic>new message</dynamic>"}
          ]
        }
      ]

      {:ok, _result} =
        Anthropic.stream_reply_with_tools(
          history,
          fn _event -> :ok end
        )

      assert_received {:api_call, 0, body}
      content_blocks = get_in(body, ["messages", Access.at(0), "content"])

      assert [
               %{
                 "type" => "text",
                 "cache_control" => %{"type" => "ephemeral", "ttl" => "1h"}
               },
               %{"type" => "text"}
             ] = content_blocks
    end
  end

  describe "max_tokens config" do
    test "sends configured max_tokens to Anthropic" do
      pid = self()

      Application.put_env(
        :froth,
        :sse_stream_fun,
        Froth.SSEReplay.recording_stream_fun("simple_reply", pid)
      )

      Application.put_env(:froth, Froth.Anthropic,
        api_key: "test-key-not-real",
        model: "claude-opus-4-6",
        max_tokens: 16_384
      )

      {:ok, _result} =
        Anthropic.stream_reply_with_tools(
          [%{role: :user, text: "hello"}],
          fn _event -> :ok end
        )

      assert_received {:api_call, 0, body}
      assert body["max_tokens"] == 16_384
    end
  end

  describe "missing API key" do
    test "returns error when no API key configured" do
      Application.put_env(:froth, Froth.Anthropic,
        api_key: nil,
        model: "claude-opus-4-6"
      )

      assert {:error, :missing_api_key} =
               Anthropic.stream_reply_with_tools(
                 [%{role: :user, text: "test"}],
                 fn _ -> :ok end
               )
    end
  end

  defp collect_events(type) do
    collect_events(type, [])
  end

  defp collect_events(type, acc) do
    receive do
      {:event, {^type, _} = event} -> collect_events(type, [event | acc])
    after
      0 -> Enum.reverse(acc)
    end
  end
end
