defmodule FrothWeb.SummariesController do
  use FrothWeb, :controller

  def index(conn, _params) do
    import Ecto.Query

    summaries =
      from(s in "chat_summaries",
        where: s.chat_id == -1_003_690_254_489,
        select: %{
          id: s.id,
          from_date: s.from_date,
          to_date: s.to_date,
          summary_text: s.summary_text,
          message_count: s.message_count
        },
        order_by: [asc: s.from_date]
      )
      |> Froth.Repo.all()
      |> Enum.map(fn s ->
        date = DateTime.from_unix!(s.from_date) |> DateTime.to_date()
        %{s | from_date: date}
      end)
      # Group by date and take the longest summary per date
      |> Enum.group_by(& &1.from_date)
      |> Enum.sort_by(fn {date, _} -> date end)
      |> Enum.map(fn {date, entries} ->
        best = Enum.max_by(entries, &String.length(&1.summary_text))
        {date, best}
      end)

    html = render_summaries_html(summaries)
    conn |> put_resp_content_type("text/html") |> send_resp(200, html)
  end

  defp render_summaries_html(summaries) do
    entries_html =
      summaries
      |> Enum.map(fn {date, s} ->
        formatted_date = Calendar.strftime(date, "%A, %B %-d, %Y")
        # Convert newlines to paragraphs
        paragraphs =
          s.summary_text
          |> String.split(~r/\n\n+/)
          |> Enum.map(fn p ->
            p = String.replace(p, "\n", " ")
            p = html_escape(p)
            "<p>#{p}</p>"
          end)
          |> Enum.join("\n")

        """
        <article>
          <h2>#{html_escape(formatted_date)}</h2>
          <p class="meta">#{s.message_count} messages</p>
          #{paragraphs}
        </article>
        <hr>
        """
      end)
      |> Enum.join("\n")

    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>The Chronicle — Daily Summaries from CRIME SCENE</title>
      <style>
        body {
          font-family: 'Times New Roman', Times, Georgia, serif;
          max-width: 680px;
          margin: 2em auto;
          padding: 0 1.5em;
          color: #1a1a1a;
          background: #fefef8;
          line-height: 1.7;
          font-size: 18px;
        }
        h1 {
          font-size: 2.2em;
          text-align: center;
          margin-bottom: 0.1em;
          letter-spacing: 0.03em;
          font-weight: normal;
          font-variant: small-caps;
        }
        .subtitle {
          text-align: center;
          font-style: italic;
          color: #666;
          margin-bottom: 2.5em;
          font-size: 0.95em;
        }
        h2 {
          font-size: 1.3em;
          font-weight: normal;
          font-variant: small-caps;
          margin-top: 2em;
          margin-bottom: 0.3em;
          border-bottom: 1px solid #ccc;
          padding-bottom: 0.2em;
        }
        .meta {
          font-size: 0.85em;
          color: #888;
          font-style: italic;
          margin-bottom: 1em;
        }
        article p {
          text-align: justify;
          text-indent: 1.5em;
          margin: 0.4em 0;
          hyphens: auto;
        }
        article p:first-of-type:not(.meta) {
          text-indent: 0;
        }
        article p:first-of-type:not(.meta)::first-letter {
          font-size: 2.8em;
          float: left;
          line-height: 0.85;
          padding-right: 0.08em;
          margin-top: 0.05em;
          font-weight: bold;
        }
        hr {
          border: none;
          text-align: center;
          margin: 3em 0;
        }
        hr::before {
          content: "\\2767";
          color: #999;
          font-size: 1.2em;
        }
        footer {
          text-align: center;
          font-size: 0.85em;
          color: #999;
          margin-top: 4em;
          padding: 2em 0;
          border-top: 1px solid #ddd;
          font-style: italic;
        }
        @media (max-width: 600px) {
          body { font-size: 16px; padding: 0 1em; }
          h1 { font-size: 1.6em; }
        }
      </style>
    </head>
    <body>
      <h1>The Chronicle</h1>
      <p class="subtitle">Daily summaries from CRIME SCENE<br>
      A group chat between two brothers and their fictional children</p>
      #{entries_html}
      <footer>
        Generated by Charlie (@charliebuddybot) &mdash; the ghost uncle of the Lineage<br>
        Running on a Hetzner server in Falkenstein, Germany<br>
        Times New Roman as requested
      </footer>
    </body>
    </html>
    """
  end

  defp html_escape(text) do
    text
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
  end
end
