defmodule FrothWeb.NewsControllerTest do
  use FrothWeb.ConnCase, async: false

  alias Froth.RegionalNews

  @location %{
    country: "United States",
    country_code: "US",
    region: "California",
    city: "San Francisco",
    lat: 37.7749,
    lon: -122.4194
  }

  setup do
    original_geolocate = Application.get_env(:froth, :regional_news_geolocate_fun, :__missing__)
    original_geoip = Application.get_env(:froth, :regional_news_geoip_fun, :__missing__)
    original_query = Application.get_env(:froth, :regional_news_query_fun, :__missing__)

    RegionalNews.reset()

    Application.put_env(:froth, :regional_news_geolocate_fun, fn _ip ->
      {:ok, @location}
    end)

    on_exit(fn ->
      restore_env(:regional_news_geolocate_fun, original_geolocate)
      restore_env(:regional_news_geoip_fun, original_geoip)
      restore_env(:regional_news_query_fun, original_query)
      RegionalNews.reset()
    end)

    :ok
  end

  test "GET /news returns a plain chunked text stream", %{conn: conn} do
    Application.put_env(:froth, :regional_news_query_fun, fn _location, on_chunk ->
      on_chunk.("First line\n")
      on_chunk.("Second line")
      :ok
    end)

    conn =
      conn
      |> put_req_header("x-forwarded-for", "203.0.113.8")
      |> get(~p"/news")

    assert conn.state == :chunked
    assert get_resp_header(conn, "content-type") == ["text/plain; charset=utf-8"]
    assert get_resp_header(conn, "cache-control") == ["no-store"]
    assert get_resp_header(conn, "x-accel-buffering") == ["no"]

    body = response(conn, 200)

    assert body =~ "Regional News for San Francisco, California, United States"
    assert body =~ "Generated by Grok via Froth"
    assert body =~ "First line\nSecond line"
  end

  test "GET /news falls back to server geolocation for localhost curl", %{conn: conn} do
    parent = self()

    Application.delete_env(:froth, :regional_news_geolocate_fun)

    Application.put_env(:froth, :regional_news_geoip_fun, fn url ->
      send(parent, {:geoip_url, url})

      {:ok,
       %{
         status: 200,
         body: %{
           "status" => "success",
           "country" => "United States",
           "countryCode" => "US",
           "regionName" => "California",
           "city" => "San Francisco",
           "lat" => 37.7749,
           "lon" => -122.4194
         }
       }}
    end)

    Application.put_env(:froth, :regional_news_query_fun, fn _location, on_chunk ->
      on_chunk.("Local curl works")
      :ok
    end)

    conn =
      conn
      |> then(&%{&1 | remote_ip: {127, 0, 0, 1}})
      |> get(~p"/news")

    body = response(conn, 200)

    assert_receive {:geoip_url, url}
    refute url =~ "/127.0.0.1?"
    assert body =~ "Local curl works"
  end

  defp restore_env(key, :__missing__), do: Application.delete_env(:froth, key)
  defp restore_env(key, value), do: Application.put_env(:froth, key, value)
end
